"""Portuguese synonym definitions for Adventure commands."""

from __future__ import annotations

from typing import Dict, List

MAPPING: Dict[str, List[str]] = {
    # Locations and navigation keywords
    "ABOVE": ["ACIMA"],
    "ACROSS": ["ATRAVES"],
    "ASCEND": ["ASCENDER"],
    "AWKWARD": ["DESAJEITADO"],
    "BACK": ["RETROCEDER", "VOLTA", "VOLTE"],
    "BARREN": ["ARIDO"],
    "BED": ["LEITO"],
    "BEDQUILT": ["COLCHA"],
    "BROKEN": ["QUEBRADO"],
    "BUILDING": ["PREDIO"],
    "CANYON": ["CANION"],
    "CAVE": ["CAVERNA"],
    "CAVERN": ["GRUTA"],
    "CLIMB": ["ESCALAR"],
    "COBBLESTONE": ["PARALELEPIPEDO"],
    "CRACK": ["FENDA"],
    "CRAWL": ["RASTEJAR"],
    "CROSS": ["CRUZAR"],
    "D": ["DESCE"],
    "DARK": ["ESCURO"],
    "DEBRIS": ["DETRITOS"],
    "DEPRESSION": ["DEPRESSAO"],
    "DESCEND": ["DESCER"],
    "DESCRIBE": ["DESCREVER"],
    "DOME": ["CUPULA"],
    "DOWN": ["ABAIXO"],
    "DOWNSTREAM": ["RIOABAIXO"],
    "DOWNWARD": ["DESCIDA"],
    "E": ["E", "L"],
    "EAST": ["LESTE", "ORIENTE"],
    "ENTER": ["ENTRAR"],
    "ENTRANCE": ["ENTRADA"],
    "EXAMINE": ["EXAMINAR", "EXAMINA", "VER"],
    "EXIT": ["SAIDA"],
    "FLOOR": ["CHAO"],
    "FOREST": ["FLORESTA"],
    "FORK": ["ENTRONCAMENTO"],
    "FORWARD": ["AVANCAR"],
    "GIANT": ["GIGANTE"],
    "GULLY": ["RAVINA"],
    "HALL": ["SALAO"],
    "HILL": ["COLINA"],
    "HOLE": ["BURACO"],
    "HOUSE": ["CASA"],
    "IN": ["DENTRO"],
    "INSIDE": ["INTERIOR"],
    "INWARD": ["ADENTRO"],
    "JUMP": ["PULAR"],
    "L": ["OBSERVAR", "OBSERVE", "OLHAR", "OLHE"],
    "LEAVE": ["SAIR"],
    "LEFT": ["ESQUERDA"],
    "LOOK": ["ESPIAR", "ESPIE"],
    "LOW": ["BAIXO"],
    "MAIN": ["PRINCIPAL"],
    "N": ["N"],
    "NE": ["NORDESTE"],
    "NORTH": ["NORTE", "SETENTRIONAL"],
    "NOWHERE": ["LUGARNEHUM"],
    "NULL": ["NULO"],
    "NW": ["NOROESTE"],
    "OFFICE": ["ESCRITORIO"],
    "ONWARD": ["ADIANTE"],
    "ORIENTAL": ["ORIENTAL"],
    "OUT": ["FORA"],
    "OUTDOORS": ["ARLIVRE"],
    "OUTSIDE": ["EXTERIOR"],
    "OVER": ["SOBRE"],
    "PASSAGE": ["PASSAGEM"],
    "PIT": ["POCO"],
    "PLOVER": ["TARAMBOLA"],
    "PLUGH": ["PLUGH"],
    "RESERVOIR": ["RESERVATORIO"],
    "RETREAT": ["RECUAR"],
    "RETURN": ["RETORNAR"],
    "RIGHT": ["DIREITA"],
    "ROAD": ["ESTRADA"],
    "ROCK": ["ROCHA"],
    "ROOM": ["SALA"],
    "S": ["S"],
    "SE": ["SUDESTE"],
    "SECRET": ["SECRETO"],
    "SHELL": ["CONCHA"],
    "SLAB": ["LAGE"],
    "SLIT": ["FRESTA"],
    "SOUTH": ["SUL", "MERIDIONAL"],
    "STAIRS": ["ESCADAS"],
    "STREAM": ["RIACHO"],
    "SURFACE": ["SUPERFICIE"],
    "SW": ["SUDOESTE"],
    "TOUCH": ["TOCAR"],
    "TUNNEL": ["TUNEL"],
    "U": ["CIMA"],
    "UP": ["SUBIR"],
    "UPSTREAM": ["RIOACIMA"],
    "UPWARD": ["PARACIMA"],
    "VALLEY": ["VALE"],
    "VIEW": ["VISTA"],
    "W": ["O"],
    "WALL": ["PAREDE"],
    "WEST": ["OESTE", "OCIDENTE"],
    "XYZZY": ["XYZZY"],

    # Objects and items
    "AXE": ["MACHADO"],
    "BARS": ["BARRAS"],
    "BATTERIES": ["PILHAS"],
    "BATTERY": ["PILHA"],
    "BEANS": ["FEIJOES"],
    "BEAR": ["URSO"],
    "BIRD": ["PASSARO"],
    "BOTTLE": ["GARRAFA"],
    "BOX": ["CAIXA"],
    "CAGE": ["GAIOLA"],
    "CARPET": ["ALCATIFA"],
    "CHAIN": ["CORRENTE"],
    "CHASM": ["ABISMO"],
    "CHEST": ["BAU"],
    "CLAM": ["AMEIJOA"],
    "COINS": ["MOEDAS"],
    "DIAMONDS": ["DIAMANTES"],
    "DOOR": ["PORTA"],
    "DRAGON": ["DRAGAO"],
    "DRAWING": ["DESENHO"],
    "DWARF": ["ANAO"],
    "DWARVES": ["ANOES"],
    "EGG": ["OVO"],
    "EGGS": ["OVOS"],
    "EMERALD": ["ESMERALDA"],
    "FIGURE": ["FIGURA"],
    "FISSURE": ["FISSURA"],
    "FOOD": ["COMIDA"],
    "GEYSER": ["GEISER"],
    "GOLD": ["OURO"],
    "GRATE": ["GRADE"],
    "H2O": ["H2O"],
    "HEADLAMP": ["LANTERNACABECA"],
    "ISSUE": ["EDICAO"],
    "JAR": ["POTE"],
    "JEWEL": ["JOIA"],
    "JEWELRY": ["JOALHERIA"],
    "JEWELS": ["ADERECOS"],
    "KEY": ["CHAVE"],
    "KEYS": ["CHAVES"],
    "KNIFE": ["FACA"],
    "KNIVES": ["FACAS"],
    "LAMP": ["LAMPADA", "LANTERNA", "LANTERNAS"],
    "LANTERN": ["LANTERNADEMAO"],
    "MACHINE": ["MAQUINA"],
    "MAGAZINE": ["REVISTA"],
    "MESSAGE": ["MENSAGEM"],
    "MING": ["MING"],
    "MIRROR": ["ESPELHO"],
    "MOSS": ["MUSGO"],
    "NEST": ["NINHO"],
    "NUGGET": ["PEPITA"],
    "OIL": ["OLEO"],
    "OYSTER": ["OSTRA"],
    "PEARL": ["PEROLA"],
    "PERSIAN": ["PERSA"],
    "PILLOW": ["TRAVESSEIRO"],
    "PIRATE": ["PIRATA"],
    "PLANT": ["PLANTA"],
    "PLATINUM": ["PLATINA"],
    "POTTERY": ["CERAMICA"],
    "PYRAMID": ["PIRAMIDE"],
    "RATIONS": ["RACOES"],
    "ROD": ["VARA"],
    "RUG": ["TAPETE"],
    "SHADOW": ["SOMBRA"],
    "SHARD": ["FRAGMENTO"],
    "SILVER": ["PRATA"],
    "SNAKE": ["COBRA"],
    "SPELUNKER": ["ESPELEOLOGO"],
    "SPELUNKER_TODAY": ["ESPELEOLOGOHOJE"],
    "SPICE": ["ESPECIARIA"],
    "SPICES": ["ESPECIARIAS"],
    "STALACTITE": ["ESTALACTITE"],
    "STEPS": ["DEGRAUS"],
    "TABLET": ["TABUA"],
    "TREASURE": ["TESOURO"],
    "TRIDENT": ["TRIDENTE"],
    "TROLL": ["TROL"],
    "VASE": ["VASO"],
    "VELVET": ["VELUDO"],
    "VENDING": ["MAQUINAVENDA"],
    "VOLCANO": ["VULCAO"],
    "WATER": ["AGUA"],

    # Verbs and commands
    "ATTACK": ["ATACAR", "ATAQUE"],
    "BLAST": ["EXPLODIR", "EXPLODA"],
    "BLOWUP": ["DEFLAGRAR", "DEFLAGRE"],
    "BREAK": ["QUEBRAR", "QUEBRE"],
    "BRIEF": ["RESUMIR", "RESUMA"],
    "CALM": ["ACALMAR", "ACALME"],
    "CAPTURE": ["CAPTURAR", "CAPTURE"],
    "CARRY": ["CARREGAR", "CARREGUE"],
    "CATCH": ["AGARRAR", "AGARRE"],
    "CHANT": ["ENTOAR", "ENTOE"],
    "CLOSE": ["FECHAR", "FECHE"],
    "CONTINUE": ["CONTINUAR", "CONTINUE"],
    "DETONATE": ["DETONAR", "DETONE"],
    "DEVOUR": ["DEVORAR", "DEVORE"],
    "DISCARD": ["DESCARTAR", "DESCARTE"],
    "DISTURB": ["PERTURBAR", "PERTURBE"],
    "DRINK": ["BEBER", "BEBA"],
    "DROP": ["LARGAR", "LARGUE", "GUARDAR"],
    "DUMP": ["DESCARREGAR", "DESCARREGUE"],
    "EAT": ["COMER", "COMA"],
    "EXPLORE": ["EXPLORAR", "EXPLORE"],
    "EXTINGUISH": ["EXTINGUIR", "EXTINGA"],
    "FEE": ["FE", "FEE"],
    "FEED": ["ALIMENTAR", "ALIMENTE"],
    "FIE": ["FI", "FIE"],
    "FIGHT": ["LUTAR", "LUTE"],
    "FILL": ["ENCHER", "ENCHA"],
    "FIND": ["ENCONTRAR", "ENCONTRE"],
    "FOE": ["FO", "FOE"],
    "FOLLOW": ["SEGUIR", "SIGA"],
    "FOO": ["FOO", "FUU"],
    "FREE": ["LIBERTAR", "LIBERTE"],
    "FUM": ["FUM", "FUMO"],
    "GET": ["PEGAR", "PEGUE", "PEGUEI", "PEGANDO"],
    "GO": ["IR", "VA", "ANDAR", "VAI", "VAMOS"],
    "GOTO": ["IRPARA", "VAPARA"],
    "HIT": ["ACERTAR", "ACERTE"],
    "HOURS": ["HORAS", "HORARIO"],
    "I": ["LISTAR", "LISTE"],
    "IGNITE": ["ACENDER", "ACENDA"],
    "INVENTORY": ["INVENTARIAR", "INVENTARIE", "INVENTARIO"],
    "KEEP": ["MANTER", "MANTENHA"],
    "KILL": ["MATAR", "MATE"],
    "LIGHT": ["ILUMINAR", "ILUMINE"],
    "LITE": ["CLAREAR", "CLAREIE"],
    "LOAD": ["CARREGARJOGO", "CARREGUEJOGO"],
    "LOCK": ["TRANCAR", "TRANQUE"],
    "LOG": ["REGISTRAR", "REGISTRE"],
    "MUMBLE": ["MURMURAR", "MURMURE"],
    "NOTHING": ["ABSTER", "ABSTENHA"],
    "OFF": ["DESLIGAR", "DESLIGUE", "APAGAR", "APAGUE"],
    "ON": ["LIGAR", "LIGUE"],
    "OPEN": ["ABRIR", "ABRE"],
    "PAUSE": ["PAUSAR", "PAUSE"],
    "PERUSE": ["ESTUDAR", "ESTUDE"],
    "PLACATE": ["APLACAR", "APLACA"],
    "POUR": ["DESPEJAR", "DESPEJE"],
    "PROCEED": ["PROSSEGUIR", "PROSSIGA"],
    "QUIT": ["ENCERRAR", "ENCERRE"],
    "READ": ["LER", "LEIA"],
    "RELEASE": ["SOLTAR", "SOLTE"],
    "RESTORE": ["RESTAURAR", "RESTAURE"],
    "RUB": ["ESFREGAR", "ESFREGUE"],
    "RUN": ["CORRER", "CORRA"],
    "SAVE": ["SALVAR", "SALVE"],
    "SAY": ["DIZER", "DIGA"],
    "SCORE": ["PONTUAR", "PONTUE"],
    "SHAKE": ["SACUDIR", "SACUDA"],
    "SHATTER": ["ESTILHACAR", "ESTILHACE"],
    "SING": ["CANTAR", "CANTE"],
    "SMASH": ["ESMAGAR", "ESMAGUE"],
    "STEAL": ["ROUBAR", "ROUBE"],
    "STRIKE": ["GOLPEAR", "GOLPEIE"],
    "SUSPEND": ["SUSPENDER", "SUSPENDA"],
    "SWING": ["BALANCAR", "BALANCE"],
    "TAKE": ["APANHAR", "APANHE"],
    "TAME": ["DOMAR", "DOME"],
    "THROW": ["ARREMESSAR", "ARREMESSE"],
    "TOSS": ["LANCAR", "LANCE"],
    "TOTE": ["TRANSPORTAR", "TRANSPORTE"],
    "TRAVEL": ["VIAJAR", "VIAJE"],
    "TURN": ["VIRAR", "VIRE"],
    "UNLOCK": ["DESTRANCAR", "DESTRANQUE"],
    "UTTER": ["PRONUNCIAR", "PRONUNCIE"],
    "WAKE": ["ACORDAR", "ACORDE"],
    "WALK": ["CAMINHAR", "CAMINHE"],
    "WAVE": ["AGITAR", "AGITE"],

    # Special words and easter eggs
    "ABRA": ["ABRA"],
    "ABRACADABRA": ["ABRACADABRA"],
    "CRAP": ["BOSTA"],
    "DAMN": ["MALDICAO"],
    "DAMNIT": ["MALDITO"],
    "DIG": ["CAVAR"],
    "EXCAVATE": ["ESCAVAR"],
    "FUCK": ["FODA"],
    "HELP": ["AJUDA"],
    "HOCUS": ["HOCUS"],
    "INFO": ["INFO"],
    "INFORMATION": ["INFORMACAO"],
    "LOST": ["PERDIDO"],
    "MIST": ["NEVOA"],
    "OPENSESAME": ["ABRETESESAMO"],
    "POCUS": ["POCUS"],
    "QUESTION": ["PERGUNTA"],
    "SESAME": ["SESAMO"],
    "SHAZAM": ["SHAZAM"],
    "SHIT": ["MERDA"],
    "STOP": ["PARAR"],
    "SWIM": ["NADAR"],
    "TREE": ["ARVORE"],
    "TREES": ["ARVORES"],
}
