name: Bob the Builder

# Run on all branches, including all pull requests, except the 'dev'
# branch since that's where we run Coverity Scan (limited tokens/day)
on:
  push:
    branches:
      - '**'
      - '!dev'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake gettext tree
      - uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DADVENTURE_WARN_AS_ERROR=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install to ~/tmp and Inspect
        run: |
          DESTDIR=~/tmp cmake --install build --strip
          tree ~/tmp
          ldd ~/tmp/usr/bin/advent
          size ~/tmp/usr/bin/advent
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git gcc cmake ninja gettext gettext-devel tree
      - name: Configure
        run: |
          cmake -S . -B build -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/mingw64 \
            -DADVENTURE_WARN_AS_ERROR=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: |
          DESTDIR=~/tmp cmake --install build --strip
          tree ~/tmp
          ldd  ~/tmp/mingw64/bin/advent.exe
          size ~/tmp/mingw64/bin/advent.exe
  debian:
    # Verify that Debian packages can be built
    name: Debian Package
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libncurses-dev cmake gettext \
                             dpkg-dev debhelper devscripts
      - name: Building Debian package
        run: |
          dpkg-buildpackage -us -uc
          echo "== advent.changes ================================================"
          cat ../advent*.changes
