name: Release General

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+*'

jobs:
  release:
    name: Build and upload release tarball
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake gettext
      - name: Creating Makefiles ...
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DADVENTURE_WARN_AS_ERROR=ON
      - name: Build release ...
        run: |
          cmake --build build --parallel
          cpack --config build/CPackSourceConfig.cmake
          mkdir -p artifacts/
          mv build/*.tar.* artifacts/
      - name: Extract ChangeLog entry ...
        run: |
          awk '/-----*/{if (x == 1) exit; x=1;next}x' ChangeLog.md \
              |head -n -1 > release.md
          cat release.md
      - uses: ncipollo/release-action@v1
        with:
          name: Colossal Cave Adventure ${{ github.ref_name }}
          bodyFile: "release.md"
          artifacts: "artifacts/*"
